before_script:
  - wget http://chromedriver.storage.googleapis.com/2.10/chromedriver_win32.zip
  - unzip chromedriver_win32.zip -d /home/travis/virtualenv/python3.8.13
  - export CHROME_BIN=chromium-browser
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 
language: python
python:
  - "3.8"
before_install:
  - pip install -U pip
install:
  - pip install -r requirements.txt
script: 
  - python -m pytest -v
after_success:
  - python deploy_ec2.py
